class_name IPA extends RefCounted

const PLOSIVE_BILABIAL_UNVOICED = preload("uid://b0vhrysvnnmuw")
const PLOSIVE_BILABIAL_VOICED = preload("uid://cx2a0e8kkc251")
const PLOSIVE_ALVEOLAR_UNVOICED = preload("uid://ck7srmkl33gxo")
const PLOSIVE_ALVEOLAR_VOICED = preload("uid://bpc3hg64s21ed")
const PLOSIVE_RETROFLEX_UNVOICED = preload("uid://jfud5bwjunyg")
const PLOSIVE_RETROFLEX_VOICED = preload("uid://c24rm2ta1r3i2")
const PLOSIVE_PALATAL_UNVOICED = preload("uid://mn4xl3dpre85")
const PLOSIVE_PALATAL_VOICED = preload("uid://bpkk3c6xfxjlu")
const PLOSIVE_VELAR_UNVOICED = preload("uid://bj7e6t1tddcyq")
const PLOSIVE_VELAR_VOICED = preload("uid://drjf4mhd8rsxj")
const PLOSIVE_UVULAR_UNVOICED = preload("uid://bs2m5avtcpb7u")
const PLOSIVE_UVULAR_VOICED = preload("uid://diva8nkm4hwh4")
const PLOSIVE_GLOTTAL = preload("uid://bf4aybdg1dl10")

const NASAL_BILABIAL = preload("uid://cbxt0ptdvgoya")
const NASAL_LABIODENTAL = preload("uid://mu6owria0ont")
const NASAL_ALVEOLAR = preload("uid://k5s8v4pq54iq")
const NASAL_RETROFLEX = preload("uid://cu1ftr1761y1h")
const NASAL_PALATAL = preload("uid://ci32getdieuxf")
const NASAL_VELAR = preload("uid://c5i05217bc1bw")
const NASAL_UVULAR = preload("uid://drgxgl05paaqo")

const TRILL_AVEOLAR = preload("uid://b61vmbpjjnf5m")
const TRILL_BILABIAL = preload("uid://do387e61ev2p1")
const TRILL_UVULAR = preload("uid://b02al4lfifvg1")

const TAP_LABIODENTAL = preload("uid://bw1rbfv86ji85")
const TAP_ALVEOLAR = preload("uid://cmg2cq5jaomfo")
const TAP_RETROFLEX = preload("uid://c8qw0kd5fbwm8")

const FRICATIVE_BILABIAL_UNVOICED = preload("uid://cuqpflct5nomd")
const FRICATIVE_BILABIAL_VOICED = preload("uid://c36s4uw3rwj7t")
const FRICATIVE_LABIODENTAL_UNVOICED = preload("uid://be4pf07yb6smy")
const FRICATIVE_LABIODENTAL_VOICED = preload("uid://sq2qnqrp8at0")
const FRICATIVE_DENTAL_UNVOICED = preload("uid://clgayy01deehh")
const FRICATIVE_DENTAL_VOICED = preload("uid://c7drq1e6s15nb")
const FRICATIVE_ALVEOLAR_UNVOICED = preload("uid://cuodtw7fnipfc")
const FRICATIVE_ALVEOLAR_VOICED = preload("uid://ckfkkt3gekp4w")
const FRICATIVE_POSTAVEOLAR_UNVOICED = preload("uid://vhuq3ireny1y")
const FRICATIVE_POSTAVEOLAR_VOICED = preload("uid://bf42w3kf1ds25")
const FRICATIVE_RETROFLEX_UNVOICED = preload("uid://c33ghe60vnrtt")
const FRICATIVE_RETROFLEX_VOICED = preload("uid://cv1d5h611iea7")
const FRICATIVE_PALATAL_UNVOICED = preload("uid://buyavndujd3mt")
const FRICATIVE_PALATAL_VOICED = preload("uid://1ai66g0w1a34")
const FRICATIVE_VELAR_UNVOICED = preload("uid://bwcfq2ig8iac7")
const FRICATIVE_VELAR_VOICED = preload("uid://g6l82tet0ovs")
const FRICATIVE_UVULAR_UNVOICED = preload("uid://dfvjmt1gyrhjl")
const FRICATIVE_UVULAR_VOICED = preload("uid://bgy5bbdhq1nmm")
const FRICATIVE_PHARYNGEAL_UNVOICED = preload("uid://detd1lvinn0s8")
const FRICATIVE_PHARYNGEAL_VOICED = preload("uid://cuafuutvoli4m")
const FRICATIVE_GLOTAL_UNVOICED = preload("uid://deaxhi2une37u")
const FRICATIVE_GLOTAL_VOICED = preload("uid://l51knfrby6to")

const FRICATIVE_LATERAL_ALVEOLAR_UNVOICED = preload("uid://kdfxi4my4fi4")
const FRICATIVE_LATERAL_ALVEOLAR_VOICED = preload("uid://bbl3fx650encr")

const APPROXIMANT_LABIALVELAR = preload("uid://b1sjpw6sjb6fs")
const APPROXIMANT_LABIODENTAL = preload("uid://cjdmgl8l517ac")
const APPROXIMANT_ALVEOLAR = preload("uid://bykqbw2coiur5")
const APPROXIMANT_RETROFLEX = preload("uid://bnyr8tn5o3tlp")
const APPROXIMANT_PALATAL = preload("uid://cf40c7flg6bnl")
const APPROXIMANT_VELAR = preload("uid://who72w0w8ewo")

const APPROXIMANT_LATERAL_ALVEOLAR = preload("uid://c8ge8a7wv55do")
const APPROXIMANT_LATERAL_RETROFLEX = preload("uid://brrt4damt4fdf")
const APPROXIMANT_LATERAL_PALATAL = preload("uid://deb0lrdru7773")
const APPROXIMANT_LATERAL_VELAR = preload("uid://diynqmxna8jin")

const VOWEL_CLOSE_FRONT_UNROUNDED = preload("uid://kgkuktosoiw7")
const VOWEL_CLOSE_FRONT_ROUNDED = preload("uid://dum4muuv104b2")
const VOWEL_CLOSE_CENTRAL_UNROUNDED = preload("uid://djj83mkgd38na")
const VOWEL_CLOSE_CENTRAL_ROUNDED = preload("uid://crmc4y34hmrsd")
const VOWEL_CLOSE_BACK_UNROUNDED = preload("uid://bch1vc817x3b7")
const VOWEL_CLOSE_BACK_ROUNDED = preload("uid://bcj0qjdmdgl4m")

const VOWEL_NEARCLOSE_NEARFRONT_UNROUNDED = preload("uid://bo04yooagqh2l")
const VOWEL_NEARCLOSE_NEARFRONT_ROUNDED = preload("uid://ccejm44jdldw6")
const VOWEL_NEARCLOSE_NEARBACK = preload("uid://cwl7mr7adwfyd")

const VOWEL_CLOSEMID_FRONT_UNROUNDED = preload("uid://do66725j8xu6l")
const VOWEL_CLOSEMID_FRONT_ROUNDED = preload("uid://cph36ayyst3ji")
const VOWEL_CLOSEMID_CENTRAL_UNROUNDED = preload("uid://cvaiyeq63yg03")
const VOWEL_CLOSEMID_CENTRAL_ROUNDED = preload("uid://dpaomlvvf3flt")
const VOWEL_CLOSEMID_BACK_UNROUNDED = preload("uid://btl0mcosg30tr")
const VOWEL_CLOSEMID_BACK_ROUNDED = preload("uid://js8l1h7ff7ja")

const VOWEL_MID_FRONT_UNROUNDED = preload("uid://bun5dscjf4ci2")
const VOWEL_MID_FRONT_ROUNDED = preload("uid://dv2rtc2yxo6xx")
const VOWEL_MID_CENTRAL = preload("uid://cepk5qvgk6lkw")
const VOWEL_MID_BACK_UNROUNDED = preload("uid://3yl3uywffwqm")
const VOWEL_MID_BACK_ROUNDED = preload("uid://wkmlgpwuamy8")

const VOWEL_OPENMID_FRONT_UNROUNDED = preload("uid://7kekxwghtege")
const VOWEL_OPENMID_FRONT_ROUNDED = preload("uid://7m3q87sbfjxu")
const VOWEL_OPENMID_CENTRAL_UNROUNDED = preload("uid://dlgj0per4e27m")
const VOWEL_OPENMID_CENTRAL_ROUNDED = preload("uid://d32ga84m3vsg2")
const VOWEL_OPENMID_BACK_UNROUNDED = preload("uid://rpkbwj3b2l2d")
const VOWEL_OPENMID_BACK_ROUNDED = preload("uid://v5tacvi468bo")

const VOWEL_NEAROPEN_FRONT_UNROUNDED = preload("uid://3wj0uclrfpx7")
const VOWEL_NEAROPEN_CENTRAL = preload("uid://b2dj5m2n7b6xe")

const VOWEL_OPEN_FRONT_UNROUNDED = preload("uid://7jvaei3tix24")
const VOWEL_OPEN_FRONT_ROUNDED = preload("uid://mdyctwqkq0ch")
const VOWEL_OPEN_CENTRAL = preload("uid://cvlytp3u2bhwt")
const VOWEL_OPEN_BACK_UNROUNDED = preload("uid://b2s2gxj6h8lli")
const VOWEL_OPEN_BACK_ROUNDED = preload("uid://dpvnt0x3skjm1")

const MODIFIER_AFFRICATIVE = preload("uid://mbhwvvisoh3o")
const MODIFIER_ASPIRATED = preload("uid://m11bhkfm455l")
const MODIFIER_EJECTIVE = preload("uid://hnbifly73qcr")
const MODIFIER_GLOTTALIZED = preload("uid://6nuxg5hxqavm")
const MODIFIER_LABIALIZED = preload("uid://blcdlacbmrudx")
const MODIFIER_PALATALIZED = preload("uid://dipi6jdloadm0")
const MODIFIER_PHARYNGEALIZED = preload("uid://bn5p2rlqx1lls")
const MODIFIER_RHOTIC_HOOK = preload("uid://carv78hals7b1")
const MODIFIER_RHOTIC_SUPERSCRIPT = preload("uid://b14qpq141gtax")
const MODIFIER_VELARIZED = preload("uid://beg004gnae3ww")

const MODIFIER_DIPHTHONG = preload("uid://b1wxqncosl0lo")
const MODIFIER_EXTRA_SHORT_VOWEL = preload("uid://cg6holwkt8lw2")
const MODIFIER_HALF_LONG_VOWEL = preload("uid://coa6g8y7mns3d")
const MODIFIER_LONG_VOWEL = preload("uid://cjkjr8kl8ofbv")

const BOUNDARY_MORPHEME = preload("uid://cmxv8mg22lv0s")
const BOUNDARY_PHONOLOGICAL_WORD = preload("uid://dt2n72sfur33t")
const BOUNDARY_SYLLABLE = preload("uid://pffx2of1mn6n")
const BOUNDARY_WORD = preload("uid://c2lmqnvv06lvj")
const STRESS_PRIMARY = preload("uid://twm84g6o8ece")
const STRESS_SECONDARY = preload("uid://bd2s0c0ppchyq")
